"""Every deliberate refusal has an identity.

Tests match a code. Prose may be reworded without breaking anything, and a differently
worded correct rejection cannot pass as a false negative.
"""

from __future__ import annotations

import enum


class RefusalReason(enum.StrEnum):
    MALFORMED_DIGEST = "malformed.digest"
    MALFORMED_IDENTIFIER = "malformed.identifier"
    MALFORMED_PACKAGE_COORDINATE = "malformed.package-coordinate"
    MALFORMED_VERDICT = "malformed.verdict"
    MALFORMED_DEVICE_NUMBER = "malformed.device-number"
    MALFORMED_STORE_MARK = "malformed.store-mark"
    MALFORMED_TREE_ROW = "malformed.tree-row"
    MALFORMED_PROOF_REFERENCE = "malformed.proof-reference"
    MALFORMED_ARTIFACT_MANIFEST = "malformed.artifact-manifest"
    MALFORMED_IMAGE_DOCUMENT = "malformed.image-document"
    MALFORMED_OCI_MANIFEST = "malformed.oci-manifest"
    MALFORMED_SCREEN_FRAME = "malformed.screen-frame"

    URL_NOT_HTTPS = "locator.url-not-https"
    FILENAME_NOT_PLAIN = "locator.filename-not-plain"

    DOWNLOAD_CHECKSUM_MISMATCH = "download.checksum-mismatch"
    NETWORK_NOT_PERMITTED = "download.network-not-permitted"

    TRUST_ANCHOR_FROM_BUNDLE = "trust.anchor-from-bundle"
    SIGNATURE_REJECTED = "trust.signature-rejected"
    BUNDLE_CONTENT_UNSIGNED = "trust.bundle-content-unsigned"
    ARTIFACT_CHECKSUM_MISMATCH = "trust.artifact-checksum-mismatch"
    SIGNED_DIGEST_MISMATCH = "trust.signed-digest-mismatch"
    IMAGE_METADATA_MISMATCH = "trust.image-metadata-mismatch"
    NEGATIVE_ACCEPTED = "trust.negative-accepted"
    NEGATIVE_WRONG_REASON = "trust.negative-wrong-reason"
    PAYLOAD_CONTRACT_INVALID = "trust.payload-contract-invalid"

    LOCK_MISSING = "lock.missing"
    LOCK_UNREADABLE = "lock.unreadable"
    LOCK_SCHEMA_UNSUPPORTED = "lock.schema-unsupported"
    LOCK_IMAGE_MISSING = "lock.image-missing"
    LOCK_IMAGE_DIGEST_MALFORMED = "lock.image-digest-malformed"
    LOCK_IMAGE_REFERENCE_MUTABLE = "lock.image-reference-mutable"
    LOCK_SOURCES_EMPTY = "lock.sources-empty"
    LOCK_ENTRY_MALFORMED = "lock.entry-malformed"
    LOCK_CHECKSUM_MALFORMED = "lock.checksum-malformed"
    LOCK_COMMIT_NOT_OBJECT_ID = "lock.commit-not-object-id"
    LOCK_FILENAME_DUPLICATE = "lock.filename-duplicate"

    NEGATIVE_QUANTITY = "quantity.negative"
    PORT_OUT_OF_RANGE = "quantity.port-out-of-range"
    MODE_OUT_OF_RANGE = "quantity.mode-out-of-range"
    LIMIT_NOT_POSITIVE = "quantity.limit-not-positive"

    PATH_OUTSIDE_RUNTIME_ROOT = "path.outside-runtime-root"
    PATH_NOT_A_REGULAR_FILE = "path.not-a-regular-file"
    PATH_NOT_A_DIRECTORY = "path.not-a-directory"
    PATH_IS_A_SYMLINK = "path.is-a-symlink"
    PATH_CONTAINS_OPTION_SEPARATOR = "path.contains-option-separator"
    RUNTIME_ROOT_NOT_PERMITTED = "path.runtime-root-not-permitted"
    RUNTIME_ROOT_NOT_PRIVATE = "path.runtime-root-not-private"

    LINE_EXCEEDS_LIMIT = "bounded.line-exceeds-limit"

    FRAME_MALFORMED = "frame.malformed"
    FRAME_OUT_OF_ORDER = "frame.out-of-order"
    FRAME_LIMIT_EXCEEDED = "frame.limit-exceeded"
    FRAME_CHECKSUM_MISMATCH = "frame.checksum-mismatch"
    FRAME_INCOMPLETE = "frame.incomplete"

    REQUEST_MALFORMED = "agent.request-malformed"
    PROTOCOL_MISMATCH = "agent.protocol-mismatch"
    UNIT_UNKNOWN = "agent.unit-unknown"
    AGENT_REFUSED = "agent.refused"

    PROBE_ENVIRONMENT_UNEXPECTED = "probe.environment-unexpected"
    SYSFS_ATTRIBUTE_MALFORMED = "probe.sysfs-attribute-malformed"
    PROBE_DESTINATION_TAKEN = "probe.destination-taken"

    DEVICE_NOT_PERMITTED_FOR_ROLE = "machine.device-not-permitted-for-role"
    DUPLICATE_DEVICE = "machine.duplicate-device"
    TOO_MANY_DEVICES = "machine.too-many-devices"
    NOT_A_DISPOSABLE_MACHINE = "machine.not-disposable"
    TOPOLOGY_INCONSISTENT = "machine.topology-inconsistent"
    SOCKET_PATH_TOO_LONG = "machine.socket-path-too-long"
    MACHINE_NOT_RUNNING = "machine.not-running"
    SERIAL_CONSOLE_ABSENT = "machine.serial-console-absent"
    FAULT_ALREADY_ATTEMPTED = "fault.already-attempted"
    FAULT_NOT_CONFIRMED = "fault.not-confirmed"
    FAULT_DISK_CHANGED = "fault.disk-changed"
    SOURCE_IMAGE_CHANGED = "fault.source-image-changed"
    MACHINE_ROLE_MISMATCH = "machine.role-mismatch"
    COMMAND_RETIRED = "command.retired"
    COMMAND_UNKNOWN = "command.unknown"
    TEST_ACCESS_NOT_QCOW2 = "build.test-access-not-qcow2"
    DEVELOPMENT_KEY_CHANGED = "trust.development-key-changed"
    PUBLIC_KEY_MALFORMED = "trust.public-key-malformed"
    MACHINE_IDENTITY_CHANGED = "machine.identity-changed"
    MACHINE_IDENTITY_UNCHECKABLE = "machine.identity-uncheckable"
    MACHINE_RUNNING = "machine.running"
    HOST_CAPACITY_INSUFFICIENT = "machine.host-capacity-insufficient"
    HOST_TOOL_MISSING = "machine.host-tool-missing"
    FIRMWARE_ABSENT = "machine.firmware-absent"
    LEASE_MALFORMED = "machine.lease-malformed"
    LEASE_MISMATCH = "machine.lease-mismatch"

    SCREEN_SIZE_CHANGED = "screen.size-changed"
    CONSOLE_TEXT_UNSUPPORTED = "console.text-unsupported"
    SESSION_ALREADY_OPEN = "desktop.session-already-open"
    CREDENTIALS_MALFORMED = "access.credentials-malformed"

    DISK_NOT_QCOW2 = "disk.not-qcow2"
    DISK_CHAIN_CYCLE = "disk.chain-cycle"
    DISK_NOT_STANDALONE = "disk.not-standalone"
    DISK_OVERLAY_EXISTS = "disk.overlay-exists"
    DEVICE_IDENTITY_MISMATCH = "device.identity-mismatch"

    FIXTURE_ENTRY_MALFORMED = "fixture.entry-malformed"
    FIXTURE_PATH_NOT_ISOLATED = "fixture.path-not-isolated"
    FIXTURE_REQUEST_MALFORMED = "fixture.request-malformed"
    FIXTURE_REPORT_MALFORMED = "fixture.report-malformed"
    FIXTURE_STATE_UNEXPECTED = "fixture.state-unexpected"
    UPDATE_STATE_UNEXPECTED = "update.state-unexpected"
    UPDATE_REJECTION_NOT_OBSERVED = "update.rejection-not-observed"
    GUEST_NOT_READY = "guest.not-ready"
    INSPECTION_MISMATCH = "initramfs.inspection-mismatch"

    LOCK_HELD = "lock.held"
    ARCHIVE_ENTRY_NOT_REGULAR = "archive.entry-not-regular"

    STAGE_FAILED = "stage.failed"

    BUILD_PROFILE_NOT_REVIEWED = "build.profile-not-reviewed"
    BUILD_PARENT_REQUIRED = "build.parent-required"
    BUILD_PARENT_NOT_COMPLETE = "build.parent-not-complete"
    BUILD_RECORD_MALFORMED = "build.record-malformed"
    NVIDIA_LOCK_MALFORMED = "build.nvidia-lock-malformed"
    NVIDIA_COMPILER_MISMATCH = "build.nvidia-compiler-mismatch"
    NVIDIA_REPORT_UNBOUND = "build.nvidia-report-unbound"
    NVIDIA_PACKAGES_INCOMPLETE = "build.nvidia-packages-incomplete"
    FINGERPRINT_LOCK_MALFORMED = "build.fingerprint-lock-malformed"
    FINGERPRINT_REPORT_UNBOUND = "build.fingerprint-report-unbound"
    FINGERPRINT_INPUT_MISMATCH = "build.fingerprint-input-mismatch"
    VENTOY_LOCK_MALFORMED = "build.ventoy-lock-malformed"
    UBUNTU_SIGNER_UNKNOWN = "trust.ubuntu-signer-unknown"
    FROZEN_IMAGE_MISMATCH = "build.frozen-image-mismatch"
    BUILDER_NOT_ISOLATED = "build.builder-not-isolated"

    HOST_RUNS_AS_ROOT = "host.runs-as-root"
    COMPACTION_INPUT_UNSAFE = "compaction.input-unsafe"
    COMPACTION_VALIDATION_FAILED = "compaction.validation-failed"
    COMPACTION_SPACE_INSUFFICIENT = "compaction.space-insufficient"
    COMPACTION_STATE_CHANGED = "compaction.state-changed"
    COMPACTION_RETAINED_INELIGIBLE = "compaction.retained-ineligible"
    PATCH_SOURCE_NOT_REVIEWED = "patch.source-not-reviewed"
    PATCH_SOURCE_UNEXPECTED = "patch.source-unexpected"

    UNKNOWN_SETTING = "settings.unknown"
    INCONSISTENT_SETTINGS = "settings.inconsistent"

    NO_VERIFIED_RESULT = "evidence.no-verified-result"
    HARDWARE_REQUIRES_PHYSICAL = "evidence.hardware-requires-physical"
    PASS_REQUIRES_PROOF = "evidence.pass-requires-proof"
    UNKNOWN_CHECK = "evidence.unknown-check"
    DUPLICATE_EVIDENCE = "evidence.duplicate"
    STALE_EVIDENCE = "evidence.stale-or-unbound"
    PROOF_KIND_NOT_ACCEPTED = "evidence.proof-kind-not-accepted"
    SIMULATED_ENVIRONMENT = "evidence.simulated-environment"
    ENVIRONMENT_NOT_WITNESSED = "evidence.environment-not-witnessed"
    RETRACTED_BY_OPERATOR = "evidence.retracted-by-operator"
    PROOF_ALTERED = "evidence.proof-altered"
    PROOF_IS_EMPTY = "evidence.proof-is-empty"
    STORE_AREA_NOT_PERMITTED = "evidence.store-area-not-permitted"
    STORE_VERSION_NOT_SUPPORTED = "evidence.store-version-not-supported"
    LEGACY_IMPORT_NOT_REPROVEN = "evidence.legacy-import-not-reproven"
    RECORD_NOT_BOUND_TO_CANDIDATE = "evidence.record-not-bound-to-candidate"

    SHELL_STRING_NOT_ACCEPTED = "command.shell-string-not-accepted"

    SECRET_NOT_RENDERABLE = "secret.not-renderable"

    VENDOR_ATTRIBUTION_PRESENT = "style.vendor-attribution-present"

    REPOSITORY_ABSOLUTE_PATH = "repository.absolute-path"
    REPOSITORY_PATH_ESCAPES = "repository.path-escapes"
    REPOSITORY_PRIVATE_DOCUMENT = "repository.private-document"
    REPOSITORY_ENVIRONMENT_FILE = "repository.environment-file"
    REPOSITORY_PRIVATE_DIRECTORY = "repository.private-directory"
    REPOSITORY_PRIVATE_ARTIFACT = "repository.private-artifact"
    REPOSITORY_CREDENTIAL_DOCUMENT = "repository.credential-document"
    REPOSITORY_PASSPHRASE_FILE = "repository.passphrase-file"
    REPOSITORY_PRIVATE_KEY_NAME = "repository.private-key-name"
    REPOSITORY_TOKEN_DOCUMENT = "repository.token-document"
    REPOSITORY_BLOB_TOO_LARGE = "repository.blob-too-large"
    REPOSITORY_BLOB_NOT_UTF8 = "repository.blob-not-utf8"
    REPOSITORY_BLOB_CONTAINS_NUL = "repository.blob-contains-nul"
    REPOSITORY_SECRET_MATERIAL = "repository.secret-material"
    REPOSITORY_LOCAL_ONLY_CONTENT = "repository.local-only-content"
    REPOSITORY_INDEX_UNMERGED = "repository.index-unmerged"
    REPOSITORY_HISTORY_NOT_FETCHED = "repository.history-not-fetched"
    REPOSITORY_UPDATE_LINE_MALFORMED = "repository.update-line-malformed"

    HOOK_ARGUMENT_MISSING = "hook.argument-missing"
    HOOK_RULES_NOT_LOADED = "hook.rules-not-loaded"
    HOOK_KIND_UNKNOWN = "hook.kind-unknown"
    HOOK_GIT_FAILED = "hook.git-failed"
    HOOK_CONTENT_UNREAD = "hook.content-unread"
    HOOK_FOREIGN = "hook.foreign-hook"
    HOOK_NO_REPOSITORY = "hook.no-repository"
    HOOK_PORTS_UNWIRED = "hook.ports-unwired"

    COMMIT_SUBJECT_MALFORMED = "commit.subject-malformed"
    COMMIT_SUBJECT_TOO_LONG = "commit.subject-too-long"
    COMMIT_HAS_BODY = "commit.has-body"
    COMMIT_CARRIAGE_RETURN = "commit.carriage-return"
    PROFILE_NOT_REVIEWED = "target.profile-not-reviewed"
