import importlib.util
import hashlib
import json
from pathlib import Path

import pytest


def probe_module():
    spec = importlib.util.spec_from_file_location('probe', Path(__file__).resolve().parents[1] / 'guest/installed-recovery-probe.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_probe_assembles_ordered_static_fragments_without_fixing_them():
    module = probe_module()
    result = module.assemble(b'pre\n', {'08.cfg': b'no-newline', '01.cfg': b'first\n', 'README': b'ignored'})
    assert result == (b'# Generated by bootupd / do not edit\n\npre\n'
                      b'\n### BEGIN 01.cfg ###\nfirst\n### END 01.cfg ###\n'
                      b'\n### BEGIN 08.cfg ###\nno-newline### END 08.cfg ###\n')
    assert b'ignored' not in result


@pytest.fixture
def installed(tmp_path, monkeypatch):
    module = probe_module()
    preset = b'GREENBOOT_MAX_BOOT_ATTEMPTS=1\n'
    fragment = b'save_env boot_success\n'
    files = {
        'run/ostree-booted': b'',
        'proc/sys/kernel/random/boot_id': b'test-boot\n',
        'usr/lib/bootupd/grub2-static/grub-static-pre.cfg': b'pre\n',
        'usr/lib/bootupd/grub2-static/configs.d/08_greenboot.cfg': fragment,
        'boot/grub2/grub.cfg': module.assemble(b'pre\n', {'08_greenboot.cfg': fragment}),
        'etc/greenboot/greenboot.conf': preset,
        'usr/share/apex/greenboot.conf': preset,
    }
    for name, content in files.items():
        path = tmp_path / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    expected = 'sha256:' + 'a' * 64
    outputs = {
        ('systemd-detect-virt', '--vm'): 'kvm\n',
        ('bootc', 'status', '--format', 'json'): json.dumps({'status': {'booted': {'image': {'imageDigest': expected}}}}),
        ('getenforce',): 'Enforcing\n',
        ('rpm', '-q', 'bootupd', 'greenboot', 'bootc'): 'test versions\n',
        ('grub2-editenv', '-', 'list'): 'boot_success=1\n',
    }
    calls = []
    def output(args, *, text):
        assert text is True
        calls.append(tuple(args))
        return outputs[tuple(args)]
    monkeypatch.setattr(module, 'Path', lambda name: tmp_path / str(name).lstrip('/'))
    monkeypatch.setattr(module.os, 'geteuid', lambda: 0)
    monkeypatch.setattr(module.subprocess, 'check_output', output)
    return module, tmp_path, expected, hashlib.sha256(preset).hexdigest(), outputs, calls


def test_installed_verification_is_read_only_and_scoped(installed):
    module, root, expected, config_sha, outputs, calls = installed
    before = {str(p): p.read_bytes() for p in root.rglob('*') if p.is_file()}
    result = module.verify(expected, config_sha)
    assert result['status'] == 'PASS'
    assert result['guest_writes'] is False
    assert result['grub_matches_image_assembly'] is True
    assert result['digest'] == expected
    assert before == {str(p): p.read_bytes() for p in root.rglob('*') if p.is_file()}
    assert set(calls) == set(outputs)


@pytest.mark.parametrize('name', ['boot/grub2/grub.cfg', 'etc/greenboot/greenboot.conf',
                                'usr/share/apex/greenboot.conf'])
def test_installed_verification_rejects_changed_configuration(installed, name):
    module, root, expected, config_sha, _, _ = installed
    path = root / name
    path.write_bytes(path.read_bytes() + b'changed\n')
    with pytest.raises(ValueError):
        module.verify(expected, config_sha)


def test_matching_but_broken_grub_is_rejected(installed):
    module, root, expected, config_sha, _, _ = installed
    fragment = b'save_env boot_success'
    (root / 'usr/lib/bootupd/grub2-static/configs.d/08_greenboot.cfg').write_bytes(fragment)
    (root / 'boot/grub2/grub.cfg').write_bytes(module.assemble(b'pre\n', {'08_greenboot.cfg': fragment}))
    with pytest.raises(ValueError, match='separator'):
        module.verify(expected, config_sha)


@pytest.mark.parametrize('command,value', [(('systemd-detect-virt', '--vm'), 'none\n'),
                                          (('getenforce',), 'Permissive\n')])
def test_installed_verification_rejects_wrong_environment(installed, command, value):
    module, _, expected, config_sha, outputs, _ = installed
    outputs[command] = value
    with pytest.raises(ValueError):
        module.verify(expected, config_sha)


def test_installed_verification_rejects_wrong_digest(installed):
    module, _, _, config_sha, _, _ = installed
    with pytest.raises(ValueError, match='digest'):
        module.verify('sha256:' + 'b' * 64, config_sha)
