"""How bootupd assembles the static GRUB configuration from its fragments.

The installed `grub.cfg` must be exactly what this assembly gives for the fragments the
image carries; a guest whose file differs has a bootloader configuration nobody reviewed.
The rule is the older probe's, kept as bytes because the comparison is bytes.
"""

from __future__ import annotations

from collections.abc import Mapping

HEADER = b"# Generated by bootupd / do not edit\n\n"
FRAGMENT_SUFFIX = ".cfg"
GREENBOOT_FRAGMENT = "08_greenboot.cfg"
SEPARATOR = b"save_env boot_success\n"


def assemble(pre: bytes, fragments: Mapping[str, bytes]) -> bytes:
    """The header, the preamble, then every `.cfg` fragment in name order, each delimited."""
    result = HEADER + pre
    for name, content in sorted(fragments.items()):
        if name.endswith(FRAGMENT_SUFFIX):
            opening = f"\n### BEGIN {name} ###\n".encode()
            closing = f"### END {name} ###\n".encode()
            result += opening + content + closing
    return result
