#!/usr/bin/python3
"""Verify installer-generated recovery configuration without changing the guest."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess


def assemble(pre, fragments):
    result = b'# Generated by bootupd / do not edit\n\n' + pre
    for name, content in sorted(fragments.items()):
        if name.endswith('.cfg'):
            result += f'\n### BEGIN {name} ###\n'.encode() + content + f'### END {name} ###\n'.encode()
    return result


def verify(expected, config_sha):
    def run(*args):
        return subprocess.check_output(args, text=True)
    if os.geteuid() or run('systemd-detect-virt', '--vm').strip() not in {'kvm', 'qemu'}:
        raise ValueError('Inspect only the installed QEMU test guest as root')
    if not Path('/run/ostree-booted').exists():
        raise ValueError('Expected an installed OSTree guest')
    status = json.loads(run('bootc', 'status', '--format', 'json'))
    if status['status']['booted']['image']['imageDigest'] != expected:
        raise ValueError('Unexpected booted digest')
    directory = Path('/usr/lib/bootupd/grub2-static')
    fragments = {p.name: p.read_bytes() for p in (directory / 'configs.d').iterdir() if p.name.endswith('.cfg')}
    installed = Path('/boot/grub2/grub.cfg').read_bytes()
    generated = assemble((directory / 'grub-static-pre.cfg').read_bytes(), fragments)
    if installed != generated:
        raise ValueError('Installed GRUB differs from the image static configuration')
    if not fragments['08_greenboot.cfg'].endswith(b'save_env boot_success\n'):
        raise ValueError('Missing GRUB fragment separator')
    paths = ['/etc/greenboot/greenboot.conf', '/usr/share/apex/greenboot.conf']
    hashes = {p: hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in paths}
    if any(value != config_sha for value in hashes.values()):
        raise ValueError('Retry configuration differs from the built fixture')
    if 'GREENBOOT_MAX_BOOT_ATTEMPTS=1\n' not in Path(paths[0]).read_text():
        raise ValueError('Expected the one-retry preset')
    if run('getenforce').strip() != 'Enforcing':
        raise ValueError('SELinux is not enforcing')
    return {'status': 'PASS', 'scope': 'Installed recovery configuration, not fault acceptance',
            'digest': expected, 'boot_id': Path('/proc/sys/kernel/random/boot_id').read_text().strip(),
            'grub_sha256': hashlib.sha256(installed).hexdigest(), 'config_sha256': hashes,
            'grub_matches_image_assembly': True, 'guest_writes': False,
            'versions': run('rpm', '-q', 'bootupd', 'greenboot', 'bootc'),
            'grubenv': run('grub2-editenv', '-', 'list'), 'bootc': status}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('expected_digest')
    parser.add_argument('config_sha256')
    args = parser.parse_args()
    print(json.dumps(verify(args.expected_digest, args.config_sha256)))
