"""The recovery probes read an installed guest and judge it the way the older scripts did."""

from __future__ import annotations

import dataclasses

import pytest
from recoveryfixtures import BOOTED, InstalledSpec, config_digest, installed_guest

from apex.adapters.fakes import fake_files
from apex.agent import grubstatic, guestguard
from apex.agent.units import recovery_installed_unit, recovery_prerequisites_unit
from apex.kernel import errors, refusals

ARGUMENTS = {"expected_digest": BOOTED, "config_sha256": config_digest(InstalledSpec())}


@pytest.fixture(autouse=True)
def as_root(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(guestguard.os, "geteuid", lambda: 0)


def test_the_assembly_orders_fragments_and_delimits_each_without_fixing_them() -> None:
    result = grubstatic.assemble(
        b"pre\n", {"08.cfg": b"no-newline", "01.cfg": b"first\n", "README": b"ignored"}
    )

    assert result == (
        b"# Generated by bootupd / do not edit\n\npre\n"
        b"\n### BEGIN 01.cfg ###\nfirst\n### END 01.cfg ###\n"
        b"\n### BEGIN 08.cfg ###\nno-newline### END 08.cfg ###\n"
    )


def test_the_prerequisites_probe_reports_every_older_section_and_never_passes() -> None:
    process, ports = installed_guest(InstalledSpec())

    report = recovery_prerequisites_unit.run(ports, arguments={})

    assert report["recovery_acceptance"] == "NOT TESTED"
    assert report["prerequisites"] == {
        "status": "NOT TESTED",
        "reasons": [],
        "note": "Two deployments alone do not prove trust, health or automatic recovery",
    }
    commands = report["commands"]
    assert isinstance(commands, dict)
    assert set(commands) == set(recovery_prerequisites_unit.COMMANDS)
    files = report["files"]
    assert isinstance(files, dict) and set(files) == set(recovery_prerequisites_unit.FILES)
    assert [tuple(call)[0] for call in process.calls][:2] == ["systemd-detect-virt", "bootc"]


@pytest.mark.parametrize(
    "spec,reasons",
    [
        (InstalledSpec(rollback=None), ["No rollback image digest"]),
        (
            InstalledSpec(rollback=BOOTED),
            ["Booted and rollback images are not distinct test deployments"],
        ),
    ],
)
def test_a_missing_or_identical_deployment_blocks_the_prerequisites(
    spec: InstalledSpec, reasons: list[str]
) -> None:
    _, ports = installed_guest(spec)

    report = recovery_prerequisites_unit.run(ports, arguments={})

    prerequisites = report["prerequisites"]
    assert isinstance(prerequisites, dict)
    assert prerequisites["status"] == "BLOCKED" and prerequisites["reasons"] == reasons


def test_a_failed_status_program_blocks_the_prerequisites() -> None:
    process, ports = installed_guest(InstalledSpec())
    process.failing.add(("bootc", "status", "--format", "json"))

    report = recovery_prerequisites_unit.run(ports, arguments={})

    prerequisites = report["prerequisites"]
    assert isinstance(prerequisites, dict) and prerequisites["reasons"] == ["bootc status failed"]


def test_outside_an_installed_guest_the_prerequisites_probe_refuses() -> None:
    _, ports = installed_guest(InstalledSpec(ostree=False))

    with pytest.raises(errors.Refusal) as caught:
        recovery_prerequisites_unit.run(ports, arguments={})

    assert caught.value.reason is refusals.RefusalReason.PROBE_ENVIRONMENT_UNEXPECTED


def test_the_installed_probe_passes_a_guest_that_matches_the_image() -> None:
    process, ports = installed_guest(InstalledSpec())

    report = recovery_installed_unit.run(ports, arguments=ARGUMENTS)

    assert report["status"] == "PASS"
    assert report["grub_matches_image_assembly"] is True
    assert report["guest_writes"] is False
    assert report["digest"] == BOOTED
    assert report["boot_id"] == "test-boot"
    assert report["versions"] == "test versions\n"
    assert report["grubenv"] == "boot_success=1\n"
    assert {tuple(call) for call in process.calls} == set(InstalledSpec().outputs)
    assert isinstance(ports.files, fake_files.MemoryFiles)
    assert ports.files.writes == list(InstalledSpec().files)


@pytest.mark.parametrize(
    "change,failure",
    [
        (
            dataclasses.replace(InstalledSpec(), grub_suffix=b"changed\n"),
            "Installed GRUB differs from the image static configuration",
        ),
        (
            dataclasses.replace(InstalledSpec(), fragment=b"save_env boot_success"),
            "Missing GRUB fragment separator",
        ),
        (
            dataclasses.replace(
                InstalledSpec(), image_preset=b"GREENBOOT_MAX_BOOT_ATTEMPTS=1\nx\n"
            ),
            "Retry configuration differs from the built fixture",
        ),
        (
            dataclasses.replace(InstalledSpec(), enforcement="Permissive"),
            "SELinux is not enforcing",
        ),
    ],
)
def test_a_configuration_that_differs_is_a_failure_that_says_what_differs(
    change: InstalledSpec, failure: str
) -> None:
    _, ports = installed_guest(change)

    report = recovery_installed_unit.run(ports, arguments=ARGUMENTS)

    assert report["status"] == "FAIL"
    assert report["failure"] == failure


def test_a_preset_that_is_not_the_one_retry_preset_fails() -> None:
    preset = b"GREENBOOT_MAX_BOOT_ATTEMPTS=2\n"
    spec = dataclasses.replace(InstalledSpec(), system_preset=preset, image_preset=preset)
    _, ports = installed_guest(spec)
    arguments = {**ARGUMENTS, "config_sha256": config_digest(spec)}

    report = recovery_installed_unit.run(ports, arguments=arguments)

    assert report["status"] == "FAIL" and report["failure"] == "Expected the one-retry preset"


def test_a_guest_booted_from_another_deployment_is_refused() -> None:
    _, ports = installed_guest(InstalledSpec(booted="sha256:" + "c" * 64))

    with pytest.raises(errors.Refusal) as caught:
        recovery_installed_unit.run(ports, arguments=ARGUMENTS)

    assert caught.value.reason is refusals.RefusalReason.PROBE_ENVIRONMENT_UNEXPECTED


@pytest.mark.parametrize(
    "arguments",
    [{}, {"expected_digest": BOOTED}, {"expected_digest": BOOTED, "config_sha256": "short"}],
)
def test_missing_or_malformed_arguments_are_refused_before_any_program(
    arguments: dict[str, str],
) -> None:
    process, ports = installed_guest(InstalledSpec())

    with pytest.raises(errors.Refusal) as caught:
        recovery_installed_unit.run(ports, arguments=arguments)

    assert caught.value.reason is refusals.RefusalReason.REQUEST_MALFORMED
    assert [tuple(call) for call in process.calls] == [("systemd-detect-virt", "--vm")]
